name: Sync Fork

on:
  schedule:
    # every day at midnight
    - cron: '0 0 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: NCCMNT
          base: main
          head: main
